#!/bin/sh
# PPM packages builder                                           
#                                                                
# (c) 2006, 2007, 2008, 2009 Piotr Roszatycki <dexter@debian.org>, Artistic   
                                                                  
# Requires:                                                      
#   Shell:                                                       
#     egrep                                                      
#     find (GNU)                                                 
#     tar (GNU)        

PERL=${PERL:-perl}

if [ -f Build.PL ]; then
    $PERL Build.PL
    $PERL Build clean
    $PERL Build.PL
    rm -f META.yml
    $PERL Build distmeta
    $PERL Build
    for cmd in $@; do $PERL Build $cmd; done
else 
    $PERL Makefile.PL
    make clean
    $PERL Makefile.PL
    make
    for cmd in $@; do make $cmd; done
fi

if [ -f Build.PL ]; then
    VERSION=`grep "^version: " META.yml | sed 's/.*: //'`
    DISTNAME=`grep "^name: " META.yml | sed 's/.*: //'`
    DISTVNAME="$DISTNAME-$VERSION"
else
    VERSION=`grep "^VERSION = " Makefile | sed 's/.* = //'`
    DISTNAME=`grep "^DISTNAME = " Makefile | sed 's/.* = //'`
    DISTVNAME=`grep "^DISTVNAME = " Makefile | sed 's/.* = //'`
fi
ARCHCOUNT=`find blib/arch -type f ! -empty | wc -l`

rm -f $DISTVNAME.ppd

if [ -f Build.PL ]; then
    $PERL Build ppd
else
    make ppd
fi

if [ $ARCHCOUNT = 0 ]; then
    cat $DISTNAME.ppd \
        | egrep -v '(OS|ARCHITECTURE) NAME=' \
        > $DISTNAME.ppd.tmp
    mv -f $DISTNAME.ppd.tmp $DISTNAME.ppd
fi

cat $DISTNAME.ppd \
    | sed -e 's,\(CODEBASE HREF="\).*",\1./'$DISTVNAME'.tgz",' \
          -e 's,\(SOFTPKG NAME=.* VERSION="\).*",\1'$VERSION'",' \
    > $DISTVNAME.ppd

rm -f $DISTNAME.ppd

if [ -f Build.PL ]; then
    rm -f PPM-*.tar.gz
    mv -f blib/bindoc blib/man1
    mv -f blib/libdoc blib/man3
    tar zcf $DISTVNAME.tgz blib
    # mv -f PPM-*.tar.gz $DISTVNAME.tgz
    # mv -f .tgz $DISTVNAME.tgz
else
    tar zcf $DISTVNAME.tgz blib
fi

exit 0
